version: "2.0"
services:
  elasticsearch:
    image: elasticsearch:7.6.1
    environment:
    - discovery.type=single-node
    ports:
    - "9200:9200"
    - "9300:9300"
  kibana:
    image: kibana:7.6.1
    ports:
    - 5601:5601
    links:
    - elasticsearch